services:
  api:
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./conf/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini

  db:
    ports:
      - "127.0.0.1:3307:3306"

  redis:
    ports:
      - "127.0.0.1:6380:6379"
