services:
  api:
    build: .
    ports:
      - "81:80"
    env_file: .env
    networks:
      - app
      - db

  db:
    image: mysql:8.0.34
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - security_db_data:/var/lib/mysql
    env_file: .env
    networks:
      - db

volumes:
  security_db_data:

networks:
  app:
    driver: bridge
  db:
    driver: bridge
