services:
  api:
    build: .
    ports:
      - "81:80"
    env_file: .env

  db:
    image: mysql:8.0.34
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - security_db_data:/var/lib/mysql
    env_file: .env

  redis:
    image: redis:alpine
    env_file: .env

volumes:
  security_db_data:
