services:
  api:
    build: .
    ports:
      - "80:80"
    networks:
      - app
      - db

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - db

networks:
  app:
    driver: bridge
  db:
    driver: bridge