services:
  api:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app
      - db

  db:
    image: mysql:8.0.34
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - db

networks:
  app:
    driver: bridge
  db:
    driver: bridge